import { NextResponse } from "next/server";
import puppeteer from "puppeteer";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { marked } from "marked";

export async function POST(request: Request) {
    try {
        // Check authentication
        const session = await getServerSession(authOptions);
        if (!session?.user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const { analysisId } = await request.json();

        if (!analysisId) {
            return NextResponse.json({ error: "Analysis ID is required" }, { status: 400 });
        }

        // Fetch analysis and report data
        const analysis = await prisma.analysis.findUnique({
            where: { id: analysisId },
            include: {
                repository: true,
                reports: true,
            },
        });

        if (!analysis || !analysis.reports || analysis.reports.length === 0) {
            return NextResponse.json({ error: "Document not found" }, { status: 404 });
        }

        // Parse the book data
        const bookData = JSON.parse(analysis.reports[0].markdown);

        // Launch Puppeteer
        const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
        });

        const page = await browser.newPage();

        // Generate HTML content for PDF
        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page {
            margin: 2cm;
            size: A4;
        }
        body {
            font-family: 'Georgia', serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
        }
        h1 {
            font-size: 32px;
            text-align: center;
            margin: 60px 0 20px 0;
            color: #1a1a1a;
        }
        h1:first-of-type {
            page-break-before: avoid;
        }
        h2 {
            font-size: 24px;
            margin: 40px 0 16px 0;
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 8px;
        }
        h3 {
            font-size: 18px;
            margin: 24px 0 12px 0;
            color: #34495e;
        }
        p {
            margin: 12px 0;
            text-align: justify;
        }
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }
        pre {
            background: #f4f4f4;
            padding: 16px;
            border-radius: 6px;
            overflow-x: auto;
            border-left: 4px solid #3498db;
        }
        pre code {
            background: none;
            padding: 0;
        }
        ul, ol {
            margin: 12px 0;
            padding-left: 30px;
        }
        li {
            margin: 6px 0;
        }
        img {
            max-width: 100%;
            height: auto;
            display: block;
            margin: 20px auto;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .title-page {
            text-align: center;
            padding: 100px 0;
            page-break-after: always;
        }
        .title-page h1 {
            font-size: 48px;
            margin-bottom: 20px;
            page-break-before: avoid;
        }
        .title-page p {
            font-size: 18px;
            color: #7f8c8d;
            font-style: italic;
        }
        .chapter {
            margin-top: 20px;
        }
        .chapter h1 {
            page-break-before: always;
        }
        .chapter:first-child h1 {
            page-break-before: avoid;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #3498db;
            color: white;
        }
        blockquote {
            border-left: 4px solid #3498db;
            margin: 20px 0;
            padding-left: 20px;
            color: #555;
            font-style: italic;
        }
    </style>
</head>
<body>
    <div class="title-page">
        <h1>${bookData.title}</h1>
        <p>Automated Technical Documentation</p>
        <p>Generated by GitDoc</p>
    </div>
    
    ${bookData.chapters.map((chapter: any, index: number) => `
        <div class="chapter">
            <h1>${chapter.title}</h1>
            ${marked.parse(chapter.content)}
        </div>
    `).join('')}
</body>
</html>
        `;

        await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

        // Generate PDF
        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: {
                top: '2cm',
                right: '2cm',
                bottom: '2cm',
                left: '2cm',
            },
        });

        await browser.close();

        // Return PDF as response
        return new NextResponse(Buffer.from(pdfBuffer), {
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="${bookData.title.replace(/[^a-z0-9]/gi, '_')}.pdf"`,
            },
        });

    } catch (error: any) {
        console.error("PDF export error:", error);
        return NextResponse.json(
            { error: error.message || "Failed to generate PDF" },
            { status: 500 }
        );
    }
}
